[tool.poetry]
name = "video-semantic-search"
version = "0.1.0"
description = ""
authors = ["Ben Tenmann <benji.tenmann@me.com>", "Sidney Radcliffe <sidneyradcliffe@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "video_semantic_search"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
streamlit = "^1.22.0"
pandas = "^2.0.1"
transformers = "^4.29.2"
torch = "^2.0.1"
torchvision = "^0.15.2"
urllib3 = "1.26.15"

[tool.poetry.group.dev.dependencies]
notebook = "^6.5.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
